Starting Nmap 5.21 ( http://nmap.org ) at 2011-03-28 16:52 EDT
Nmap scan report for core6509.townisp.com (216.195.0.1)
Host is up (0.17s latency).
Not shown: 999 closed ports
PORT     STATE    SERVICE
1720/tcp filtered H.323/Q.931

Nmap scan report for vodfw.townisp.com (216.195.0.5)
Host is up (0.23s latency).
Not shown: 999 closed ports
PORT     STATE    SERVICE
1720/tcp filtered H.323/Q.931

Nmap scan report for core6509-2.townisp.com (216.195.0.10)
Host is up (0.17s latency).
Not shown: 999 closed ports
PORT     STATE    SERVICE
1720/tcp filtered H.323/Q.931

Nmap scan report for ubr10k-1.townisp.com (216.195.0.11)
Host is up (0.18s latency).
Not shown: 998 closed ports
PORT     STATE    SERVICE
1720/tcp filtered H.323/Q.931
2126/tcp open     unknown

Nmap scan report for ubr10k-2.townisp.com (216.195.0.13)
Host is up (0.20s latency).
Not shown: 998 closed ports
PORT     STATE    SERVICE
1720/tcp filtered H.323/Q.931
2126/tcp open     unknown

Nmap scan report for core6509-bgp.townisp.com (216.195.0.17)
Host is up (0.18s latency).
Not shown: 999 closed ports
PORT     STATE    SERVICE
1720/tcp filtered H.323/Q.931

Nmap scan report for core6509-2-bgp.townisp.com (216.195.0.20)
Host is up (0.27s latency).
Not shown: 999 closed ports
PORT     STATE    SERVICE
1720/tcp filtered H.323/Q.931

Nmap scan report for ubr10k-1-bgp.townisp.com (216.195.0.22)
Host is up (0.069s latency).
Not shown: 998 closed ports
PORT     STATE    SERVICE
1720/tcp filtered H.323/Q.931
2126/tcp open     unknown

Nmap scan report for ubr10k-2-bgp.townisp.com (216.195.0.23)
Host is up (0.030s latency).
Not shown: 998 closed ports
PORT     STATE    SERVICE
1720/tcp filtered H.323/Q.931
2126/tcp open     unknown

Nmap scan report for gis.shrewsbury-ma.gov.shrewsbury-ma.gov (216.195.0.37)
Host is up (0.13s latency).
Not shown: 998 filtered ports
PORT    STATE  SERVICE
80/tcp  open   http
443/tcp closed https

Nmap scan report for outlook.shrewsbury-ma.gov (216.195.0.38)
Host is up (0.20s latency).
Not shown: 997 filtered ports
PORT    STATE SERVICE
25/tcp  open  smtp
80/tcp  open  http
443/tcp open  https

Nmap scan report for webmail.shrewsbury.k12.ma.us (216.195.0.41)
Host is up (0.15s latency).
Not shown: 998 filtered ports
PORT    STATE SERVICE
80/tcp  open  http
443/tcp open  https

Nmap scan report for 216.195.0.49
Host is up (0.046s latency).
Not shown: 992 closed ports
PORT     STATE    SERVICE
135/tcp  filtered msrpc
139/tcp  filtered netbios-ssn
445/tcp  filtered microsoft-ds
1025/tcp filtered NFS-or-IIS
1026/tcp filtered LSA-or-nterm
1027/tcp filtered IIS
1720/tcp filtered H.323/Q.931
4444/tcp filtered krb524

Nmap scan report for 216.195.0.50
Host is up (0.032s latency).
Not shown: 970 closed ports
PORT      STATE    SERVICE
80/tcp    open     http
125/tcp   open     locus-map
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
443/tcp   open     https
445/tcp   filtered microsoft-ds
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1037/tcp  open     unknown
1079/tcp  open     unknown
1147/tcp  open     unknown
1300/tcp  open     unknown
1556/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
2005/tcp  open     deslogin
2323/tcp  open     unknown
2717/tcp  open     unknown
3869/tcp  open     unknown
3880/tcp  open     unknown
4444/tcp  filtered krb524
5811/tcp  open     unknown
5902/tcp  open     vnc-2
6788/tcp  open     unknown
6881/tcp  open     bittorrent-tracker
8652/tcp  open     unknown
9101/tcp  open     jetdirect
10626/tcp open     unknown
32774/tcp filtered sometimes-rpc11
44443/tcp open     coldfusion-auth

Nmap scan report for 216.195.0.53
Host is up (0.057s latency).
Not shown: 999 closed ports
PORT     STATE    SERVICE
1720/tcp filtered H.323/Q.931

Nmap scan report for 216.195.0.54
Host is up (0.24s latency).
Not shown: 999 closed ports
PORT     STATE    SERVICE
1720/tcp filtered H.323/Q.931

Nmap scan report for 216.195.0.64
Host is up (0.21s latency).
Not shown: 969 closed ports
PORT      STATE    SERVICE
125/tcp   open     locus-map
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
416/tcp   open     silverplatter
445/tcp   filtered microsoft-ds
515/tcp   open     printer
992/tcp   open     telnets
995/tcp   open     pop3s
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1033/tcp  open     netinfo
1067/tcp  open     instl_boots
1093/tcp  open     unknown
1113/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
2179/tcp  open     unknown
2323/tcp  open     unknown
3869/tcp  open     unknown
4125/tcp  open     rww
4444/tcp  filtered krb524
5718/tcp  open     unknown
5811/tcp  open     unknown
6123/tcp  open     unknown
6881/tcp  open     bittorrent-tracker
7025/tcp  open     unknown
8291/tcp  open     unknown
9040/tcp  open     tor-trans
10012/tcp open     unknown
44443/tcp open     coldfusion-auth
58080/tcp open     unknown

Nmap scan report for 216.195.0.65
Host is up (0.044s latency).
Not shown: 971 closed ports
PORT      STATE    SERVICE
33/tcp    open     dsp
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
416/tcp   open     silverplatter
445/tcp   filtered microsoft-ds
992/tcp   open     telnets
995/tcp   open     pop3s
1009/tcp  open     unknown
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1113/tcp  open     unknown
1719/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
2323/tcp  open     unknown
3869/tcp  open     unknown
3880/tcp  open     unknown
4444/tcp  filtered krb524
5811/tcp  open     unknown
6788/tcp  open     unknown
8099/tcp  open     unknown
8180/tcp  open     unknown
9101/tcp  open     jetdirect
10012/tcp open     unknown
13782/tcp open     netbackup
13783/tcp open     netbackup
22939/tcp open     unknown
44443/tcp open     coldfusion-auth
54045/tcp open     unknown

Nmap scan report for 216.195.0.66
Host is up (0.15s latency).
Not shown: 958 closed ports
PORT      STATE    SERVICE
9/tcp     open     discard
111/tcp   open     rpcbind
119/tcp   open     nntp
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
163/tcp   open     cmip-man
445/tcp   filtered microsoft-ds
999/tcp   open     garcon
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1033/tcp  open     netinfo
1055/tcp  open     ansyslmd
1067/tcp  open     instl_boots
1082/tcp  open     unknown
1166/tcp  open     unknown
1641/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
1723/tcp  open     pptp
1935/tcp  open     rtmp
2042/tcp  open     isis
2522/tcp  open     unknown
3324/tcp  open     unknown
3370/tcp  open     unknown
4444/tcp  filtered krb524
5001/tcp  open     commplex-link
5963/tcp  open     unknown
6123/tcp  open     unknown
8084/tcp  open     unknown
8086/tcp  open     unknown
8087/tcp  open     unknown
8089/tcp  open     unknown
8180/tcp  open     unknown
8443/tcp  open     https-alt
8654/tcp  open     unknown
9040/tcp  open     tor-trans
13783/tcp open     netbackup
21571/tcp open     unknown
50003/tcp open     unknown
50389/tcp open     unknown
52848/tcp open     unknown
61900/tcp open     unknown

Nmap scan report for 216.195.0.67
Host is up (0.20s latency).
Not shown: 971 closed ports
PORT      STATE    SERVICE
109/tcp   open     pop2
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
416/tcp   open     silverplatter
445/tcp   filtered microsoft-ds
992/tcp   open     telnets
999/tcp   open     garcon
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1033/tcp  open     netinfo
1082/tcp  open     unknown
1217/tcp  open     unknown
1641/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
1862/tcp  filtered unknown
2042/tcp  open     isis
2638/tcp  open     sybase
3998/tcp  open     unknown
4444/tcp  filtered krb524
4662/tcp  open     edonkey
5001/tcp  open     commplex-link
5679/tcp  open     activesync
8087/tcp  open     unknown
8089/tcp  open     unknown
8443/tcp  open     https-alt
8654/tcp  open     unknown
10012/tcp open     unknown
16992/tcp open     unknown

Nmap scan report for 216.195.0.68
Host is up (0.13s latency).
Not shown: 978 closed ports
PORT      STATE    SERVICE
125/tcp   open     locus-map
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
445/tcp   filtered microsoft-ds
515/tcp   open     printer
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1093/tcp  open     unknown
1141/tcp  open     unknown
1217/tcp  open     unknown
1719/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
2323/tcp  open     unknown
4125/tcp  open     rww
4444/tcp  filtered krb524
6788/tcp  open     unknown
8291/tcp  open     unknown
13782/tcp open     netbackup
16992/tcp open     unknown
44443/tcp open     coldfusion-auth
58080/tcp open     unknown

Nmap scan report for 216.195.0.69
Host is up (0.11s latency).
Not shown: 968 closed ports
PORT      STATE    SERVICE
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
445/tcp   filtered microsoft-ds
999/tcp   open     garcon
1009/tcp  open     unknown
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1093/tcp  open     unknown
1112/tcp  open     msql
1113/tcp  open     unknown
1151/tcp  open     unknown
1300/tcp  open     unknown
1719/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
3261/tcp  open     unknown
3869/tcp  open     unknown
3880/tcp  open     unknown
4125/tcp  open     rww
4444/tcp  filtered krb524
5811/tcp  open     unknown
6788/tcp  open     unknown
8084/tcp  open     unknown
8099/tcp  open     unknown
8291/tcp  open     unknown
8652/tcp  open     unknown
9101/tcp  open     jetdirect
10626/tcp open     unknown
22939/tcp open     unknown
40193/tcp open     unknown
52848/tcp open     unknown
54045/tcp open     unknown

Nmap scan report for 216.195.0.70
Host is up (0.21s latency).
Not shown: 971 closed ports
PORT      STATE    SERVICE
119/tcp   open     nntp
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
445/tcp   filtered microsoft-ds
999/tcp   open     garcon
1023/tcp  open     netvenuechat
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1055/tcp  open     ansyslmd
1067/tcp  open     instl_boots
1082/tcp  open     unknown
1112/tcp  open     msql
1117/tcp  open     unknown
1641/tcp  open     unknown
1718/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
1935/tcp  open     rtmp
2042/tcp  open     isis
2638/tcp  open     sybase
3493/tcp  open     unknown
3998/tcp  open     unknown
4444/tcp  filtered krb524
4662/tcp  open     edonkey
5001/tcp  open     commplex-link
8089/tcp  open     unknown
8443/tcp  open     https-alt
8654/tcp  open     unknown
52848/tcp open     unknown

Nmap scan report for 216.195.0.71
Host is up (0.18s latency).
Not shown: 974 closed ports
PORT      STATE    SERVICE
125/tcp   open     locus-map
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
416/tcp   open     silverplatter
445/tcp   filtered microsoft-ds
901/tcp   open     samba-swat
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1141/tcp  open     unknown
1217/tcp  open     unknown
1322/tcp  open     unknown
1719/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
2179/tcp  open     unknown
2323/tcp  open     unknown
2607/tcp  open     unknown
4444/tcp  filtered krb524
5718/tcp  open     unknown
6788/tcp  open     unknown
7007/tcp  open     afs3-bos
7025/tcp  open     unknown
9040/tcp  open     tor-trans
10012/tcp open     unknown
44443/tcp open     coldfusion-auth
58080/tcp open     unknown

Nmap scan report for 216.195.0.72
Host is up (0.18s latency).
Not shown: 968 closed ports
PORT      STATE    SERVICE
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
445/tcp   filtered microsoft-ds
1009/tcp  open     unknown
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1055/tcp  open     ansyslmd
1093/tcp  open     unknown
1113/tcp  open     unknown
1151/tcp  open     unknown
1300/tcp  open     unknown
1719/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
1935/tcp  open     rtmp
3261/tcp  open     unknown
3493/tcp  open     unknown
3869/tcp  open     unknown
3880/tcp  open     unknown
4444/tcp  filtered krb524
5811/tcp  open     unknown
6788/tcp  open     unknown
8084/tcp  open     unknown
8099/tcp  open     unknown
8180/tcp  open     unknown
8291/tcp  open     unknown
9101/tcp  open     jetdirect
13783/tcp open     netbackup
22939/tcp open     unknown
40193/tcp open     unknown
52848/tcp open     unknown
54045/tcp open     unknown

Nmap scan report for 216.195.0.73
Host is up (0.22s latency).
Not shown: 965 closed ports
PORT      STATE    SERVICE
22/tcp    open     ssh
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
366/tcp   filtered odmr
416/tcp   open     silverplatter
445/tcp   filtered microsoft-ds
901/tcp   open     samba-swat
992/tcp   open     telnets
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1033/tcp  open     netinfo
1082/tcp  open     unknown
1093/tcp  open     unknown
1141/tcp  open     unknown
1309/tcp  open     unknown
1322/tcp  open     unknown
1718/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
2323/tcp  open     unknown
2601/tcp  open     zebra
2607/tcp  open     unknown
2638/tcp  open     sybase
3869/tcp  open     unknown
3998/tcp  open     unknown
4125/tcp  open     rww
4444/tcp  filtered krb524
6123/tcp  open     unknown
6788/tcp  open     unknown
7007/tcp  open     afs3-bos
7025/tcp  open     unknown
9040/tcp  open     tor-trans
10012/tcp open     unknown
45100/tcp open     unknown
58080/tcp open     unknown

Nmap scan report for 216.195.0.74
Host is up (0.27s latency).
Not shown: 967 closed ports
PORT      STATE    SERVICE
53/tcp    open     domain
125/tcp   open     locus-map
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
445/tcp   filtered microsoft-ds
901/tcp   open     samba-swat
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1082/tcp  open     unknown
1093/tcp  open     unknown
1141/tcp  open     unknown
1147/tcp  open     unknown
1217/tcp  open     unknown
1309/tcp  open     unknown
1322/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
2323/tcp  open     unknown
2607/tcp  open     unknown
2638/tcp  open     sybase
3998/tcp  open     unknown
4125/tcp  open     rww
4444/tcp  filtered krb524
6123/tcp  open     unknown
6881/tcp  open     bittorrent-tracker
7007/tcp  open     afs3-bos
7025/tcp  open     unknown
9040/tcp  open     tor-trans
10626/tcp open     unknown
16992/tcp open     unknown
44443/tcp open     coldfusion-auth
45100/tcp open     unknown
58080/tcp open     unknown

Nmap scan report for 216.195.0.75
Host is up (0.029s latency).
Not shown: 948 filtered ports
PORT      STATE  SERVICE
22/tcp    open   ssh
33/tcp    open   dsp
80/tcp    closed http
111/tcp   open   rpcbind
125/tcp   open   locus-map
416/tcp   open   silverplatter
443/tcp   closed https
515/tcp   open   printer
587/tcp   open   submission
992/tcp   open   telnets
995/tcp   open   pop3s
999/tcp   open   garcon
1033/tcp  open   netinfo
1037/tcp  open   unknown
1055/tcp  open   ansyslmd
1067/tcp  open   instl_boots
1079/tcp  open   unknown
1082/tcp  open   unknown
1112/tcp  open   msql
1217/tcp  open   unknown
1322/tcp  open   unknown
1556/tcp  open   unknown
1719/tcp  open   unknown
1723/tcp  open   pptp
2005/tcp  open   deslogin
2179/tcp  open   unknown
2323/tcp  open   unknown
2638/tcp  open   sybase
2717/tcp  open   unknown
3001/tcp  open   nessus
3869/tcp  open   unknown
3998/tcp  open   unknown
5811/tcp  open   unknown
5902/tcp  open   vnc-2
6123/tcp  open   unknown
6881/tcp  open   bittorrent-tracker
7025/tcp  open   unknown
8080/tcp  open   http-proxy
8084/tcp  open   unknown
8087/tcp  open   unknown
8180/tcp  open   unknown
8291/tcp  open   unknown
8654/tcp  open   unknown
9011/tcp  open   unknown
9040/tcp  open   tor-trans
10012/tcp open   unknown
13782/tcp open   netbackup
13783/tcp open   netbackup
16992/tcp open   unknown
41511/tcp open   unknown
44443/tcp open   coldfusion-auth
50389/tcp open   unknown

Nmap scan report for 216.195.0.76
Host is up (0.11s latency).
Not shown: 957 closed ports
PORT      STATE    SERVICE
9/tcp     open     discard
22/tcp    open     ssh
82/tcp    open     xfer
119/tcp   open     nntp
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
443/tcp   open     https
445/tcp   filtered microsoft-ds
513/tcp   open     login
992/tcp   open     telnets
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1033/tcp  open     netinfo
1067/tcp  open     instl_boots
1102/tcp  open     unknown
1217/tcp  open     unknown
1556/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
1839/tcp  open     unknown
1935/tcp  open     rtmp
2001/tcp  open     dc
2005/tcp  open     deslogin
2103/tcp  open     zephyr-clt
2717/tcp  open     unknown
3017/tcp  open     unknown
3283/tcp  open     netassistant
3324/tcp  open     unknown
4003/tcp  open     unknown
4444/tcp  filtered krb524
5003/tcp  open     filemaker
5902/tcp  open     vnc-2
5962/tcp  open     unknown
6123/tcp  open     unknown
8087/tcp  open     unknown
8093/tcp  open     unknown
8180/tcp  open     unknown
9418/tcp  open     git
13783/tcp open     netbackup
16992/tcp open     unknown
21571/tcp open     unknown
50389/tcp open     unknown
61900/tcp open     unknown

Nmap scan report for 216.195.0.77
Host is up (0.080s latency).
Not shown: 954 closed ports
PORT      STATE    SERVICE
9/tcp     open     discard
109/tcp   open     pop2
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
445/tcp   filtered microsoft-ds
667/tcp   open     unknown
992/tcp   open     telnets
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1033/tcp  open     netinfo
1102/tcp  open     unknown
1300/tcp  open     unknown
1556/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
2005/tcp  open     deslogin
2034/tcp  open     scoremgr
2048/tcp  open     dls-monitor
2103/tcp  open     zephyr-clt
2522/tcp  open     unknown
2717/tcp  open     unknown
3001/tcp  open     nessus
3017/tcp  open     unknown
3324/tcp  open     unknown
3880/tcp  open     unknown
4001/tcp  open     unknown
4444/tcp  filtered krb524
5679/tcp  open     activesync
5902/tcp  open     vnc-2
6005/tcp  open     X11:5
6156/tcp  open     unknown
8087/tcp  open     unknown
8192/tcp  open     sophos
9011/tcp  open     unknown
9877/tcp  open     unknown
10002/tcp open     unknown
10012/tcp open     unknown
13783/tcp open     netbackup
16992/tcp open     unknown
20828/tcp open     unknown
21571/tcp open     unknown
25734/tcp open     unknown
49400/tcp open     compaqdiag
50003/tcp open     unknown
50389/tcp open     unknown
61900/tcp open     unknown

Nmap scan report for 216.195.0.78
Host is up (0.028s latency).
Not shown: 974 closed ports
PORT      STATE    SERVICE
119/tcp   open     nntp
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
445/tcp   filtered microsoft-ds
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1151/tcp  open     unknown
1300/tcp  open     unknown
1322/tcp  open     unknown
1556/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
1935/tcp  open     rtmp
2005/tcp  open     deslogin
2179/tcp  open     unknown
2522/tcp  open     unknown
2717/tcp  open     unknown
3001/tcp  open     nessus
4444/tcp  filtered krb524
5902/tcp  open     vnc-2
6156/tcp  open     unknown
7025/tcp  open     unknown
9011/tcp  open     unknown
21571/tcp open     unknown
50003/tcp open     unknown
61900/tcp open     unknown

Nmap scan report for 216.195.0.79
Host is up (0.074s latency).
Not shown: 957 closed ports
PORT      STATE    SERVICE
22/tcp    open     ssh
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
416/tcp   open     silverplatter
443/tcp   open     https
445/tcp   filtered microsoft-ds
992/tcp   open     telnets
1009/tcp  open     unknown
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1033/tcp  open     netinfo
1217/tcp  open     unknown
1300/tcp  open     unknown
1719/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
2005/tcp  open     deslogin
2034/tcp  open     scoremgr
2323/tcp  open     unknown
2522/tcp  open     unknown
3324/tcp  open     unknown
3869/tcp  open     unknown
3880/tcp  open     unknown
4444/tcp  filtered krb524
5811/tcp  open     unknown
5902/tcp  open     vnc-2
6005/tcp  open     X11:5
6156/tcp  open     unknown
6788/tcp  open     unknown
8099/tcp  open     unknown
8180/tcp  open     unknown
8192/tcp  open     sophos
9101/tcp  open     jetdirect
9877/tcp  open     unknown
10002/tcp open     unknown
10012/tcp open     unknown
13783/tcp open     netbackup
20828/tcp open     unknown
22939/tcp open     unknown
49400/tcp open     compaqdiag
50003/tcp open     unknown
50389/tcp open     unknown
54045/tcp open     unknown

Nmap scan report for 216.195.0.80
Host is up (0.055s latency).
Not shown: 956 closed ports
PORT      STATE    SERVICE
119/tcp   open     nntp
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
264/tcp   open     bgmp
445/tcp   filtered microsoft-ds
995/tcp   open     pop3s
1009/tcp  open     unknown
1011/tcp  open     unknown
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1033/tcp  open     netinfo
1065/tcp  open     unknown
1067/tcp  open     instl_boots
1093/tcp  open     unknown
1104/tcp  open     unknown
1113/tcp  open     unknown
1287/tcp  open     unknown
1300/tcp  open     unknown
1556/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
1935/tcp  open     rtmp
2005/tcp  open     deslogin
2046/tcp  open     sdfunc
2717/tcp  open     unknown
2875/tcp  open     unknown
3001/tcp  open     nessus
3880/tcp  open     unknown
3920/tcp  open     unknown
4125/tcp  open     rww
4444/tcp  filtered krb524
5902/tcp  open     vnc-2
5952/tcp  open     unknown
6969/tcp  open     acmsoda
7938/tcp  open     lgtomapper
8087/tcp  open     unknown
8099/tcp  open     unknown
9101/tcp  open     jetdirect
21571/tcp open     unknown
22939/tcp open     unknown
48080/tcp open     unknown
54045/tcp open     unknown
58080/tcp open     unknown
61900/tcp open     unknown

Nmap scan report for 216.195.0.81
Host is up (0.15s latency).
Not shown: 971 closed ports
PORT      STATE    SERVICE
9/tcp     open     discard
22/tcp    open     ssh
125/tcp   open     locus-map
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
416/tcp   open     silverplatter
445/tcp   filtered microsoft-ds
992/tcp   open     telnets
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1067/tcp  open     instl_boots
1556/tcp  open     unknown
1641/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
2005/tcp  open     deslogin
2103/tcp  open     zephyr-clt
2179/tcp  open     unknown
2323/tcp  open     unknown
2717/tcp  open     unknown
3001/tcp  open     nessus
4444/tcp  filtered krb524
5001/tcp  open     commplex-link
5718/tcp  open     unknown
8089/tcp  open     unknown
9011/tcp  open     unknown
9999/tcp  filtered abyss
10012/tcp open     unknown
44443/tcp open     coldfusion-auth

Nmap scan report for 216.195.0.82
Host is up (0.14s latency).
Not shown: 972 closed ports
PORT      STATE    SERVICE
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
445/tcp   filtered microsoft-ds
901/tcp   open     samba-swat
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1037/tcp  open     unknown
1067/tcp  open     instl_boots
1079/tcp  open     unknown
1141/tcp  open     unknown
1151/tcp  open     unknown
1217/tcp  open     unknown
1719/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
2601/tcp  open     zebra
2607/tcp  open     unknown
2717/tcp  open     unknown
3001/tcp  open     nessus
4444/tcp  filtered krb524
6123/tcp  open     unknown
6788/tcp  open     unknown
7007/tcp  open     afs3-bos
8087/tcp  open     unknown
9011/tcp  open     unknown
16992/tcp open     unknown
40193/tcp open     unknown
41511/tcp open     unknown

Nmap scan report for 216.195.0.83
Host is up (0.068s latency).
Not shown: 953 closed ports
PORT      STATE    SERVICE
119/tcp   open     nntp
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
445/tcp   filtered microsoft-ds
667/tcp   open     unknown
992/tcp   open     telnets
995/tcp   open     pop3s
999/tcp   open     garcon
1009/tcp  open     unknown
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1033/tcp  open     netinfo
1093/tcp  open     unknown
1113/tcp  open     unknown
1138/tcp  open     unknown
1217/tcp  open     unknown
1719/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
2005/tcp  open     deslogin
2034/tcp  open     scoremgr
2048/tcp  open     dls-monitor
3869/tcp  open     unknown
3880/tcp  open     unknown
4001/tcp  open     unknown
4444/tcp  filtered krb524
5902/tcp  open     vnc-2
6005/tcp  open     X11:5
6788/tcp  open     unknown
8080/tcp  open     http-proxy
8084/tcp  open     unknown
8099/tcp  open     unknown
8180/tcp  open     unknown
8192/tcp  open     sophos
9101/tcp  open     jetdirect
9877/tcp  open     unknown
10002/tcp open     unknown
13783/tcp open     netbackup
20828/tcp open     unknown
21571/tcp open     unknown
22939/tcp open     unknown
25734/tcp open     unknown
49400/tcp open     compaqdiag
50389/tcp open     unknown
54045/tcp open     unknown
61532/tcp open     unknown
61900/tcp open     unknown

Nmap scan report for 216.195.0.84
Host is up (0.25s latency).
Not shown: 964 closed ports
PORT      STATE    SERVICE
125/tcp   open     locus-map
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
163/tcp   open     cmip-man
416/tcp   open     silverplatter
445/tcp   filtered microsoft-ds
515/tcp   open     printer
992/tcp   open     telnets
999/tcp   open     garcon
1023/tcp  open     netvenuechat
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1033/tcp  open     netinfo
1082/tcp  open     unknown
1117/tcp  open     unknown
1166/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
2007/tcp  open     dectalk
2323/tcp  open     unknown
2638/tcp  open     sybase
3905/tcp  open     mupdate
3998/tcp  open     unknown
4444/tcp  filtered krb524
5811/tcp  open     unknown
6881/tcp  open     bittorrent-tracker
8084/tcp  open     unknown
8086/tcp  open     unknown
8180/tcp  open     unknown
8291/tcp  open     unknown
8500/tcp  open     unknown
8654/tcp  open     unknown
10012/tcp open     unknown
14442/tcp open     unknown
32781/tcp open     unknown
44443/tcp open     coldfusion-auth

Nmap scan report for 216.195.0.85
Host is up (0.28s latency).
Not shown: 971 closed ports
PORT      STATE    SERVICE
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
445/tcp   filtered microsoft-ds
515/tcp   open     printer
901/tcp   open     samba-swat
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1082/tcp  open     unknown
1141/tcp  open     unknown
1147/tcp  open     unknown
1322/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
2179/tcp  open     unknown
2638/tcp  open     sybase
3869/tcp  open     unknown
3998/tcp  open     unknown
4444/tcp  filtered krb524
5718/tcp  open     unknown
5811/tcp  open     unknown
6881/tcp  open     bittorrent-tracker
7025/tcp  open     unknown
8291/tcp  open     unknown
8652/tcp  open     unknown
9011/tcp  open     unknown
9040/tcp  open     tor-trans
10626/tcp open     unknown
13782/tcp open     netbackup
58080/tcp open     unknown

Nmap scan report for 216.195.0.86
Host is up (0.20s latency).
Not shown: 965 closed ports
PORT      STATE    SERVICE
9/tcp     open     discard
109/tcp   open     pop2
125/tcp   open     locus-map
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
163/tcp   open     cmip-man
443/tcp   open     https
445/tcp   filtered microsoft-ds
999/tcp   open     garcon
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1082/tcp  open     unknown
1166/tcp  open     unknown
1641/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
2103/tcp  open     zephyr-clt
2323/tcp  open     unknown
3370/tcp  open     unknown
3869/tcp  open     unknown
3998/tcp  open     unknown
4444/tcp  filtered krb524
5001/tcp  open     commplex-link
5679/tcp  open     activesync
5811/tcp  open     unknown
5963/tcp  open     unknown
6881/tcp  open     bittorrent-tracker
8084/tcp  open     unknown
8086/tcp  open     unknown
8089/tcp  open     unknown
8180/tcp  open     unknown
8443/tcp  open     https-alt
8654/tcp  open     unknown
13783/tcp open     netbackup
44443/tcp open     coldfusion-auth

Nmap scan report for 216.195.0.87
Host is up (0.28s latency).
Not shown: 964 closed ports
PORT      STATE    SERVICE
119/tcp   open     nntp
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
163/tcp   open     cmip-man
416/tcp   open     silverplatter
443/tcp   open     https
445/tcp   filtered microsoft-ds
515/tcp   open     printer
992/tcp   open     telnets
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1033/tcp  open     netinfo
1166/tcp  open     unknown
1322/tcp  open     unknown
1641/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
2007/tcp  open     dectalk
2638/tcp  open     sybase
3370/tcp  open     unknown
3945/tcp  open     unknown
3998/tcp  open     unknown
4444/tcp  filtered krb524
5001/tcp  open     commplex-link
5811/tcp  open     unknown
5963/tcp  open     unknown
8086/tcp  open     unknown
8089/tcp  open     unknown
8291/tcp  open     unknown
8443/tcp  open     https-alt
8500/tcp  open     unknown
10012/tcp open     unknown
14442/tcp open     unknown
21571/tcp open     unknown
32781/tcp open     unknown
61900/tcp open     unknown

Nmap scan report for 216.195.0.88
Host is up (0.027s latency).
Not shown: 929 filtered ports
PORT      STATE  SERVICE
21/tcp    open   ftp
22/tcp    open   ssh
23/tcp    open   telnet
25/tcp    open   smtp
33/tcp    open   dsp
53/tcp    open   domain
80/tcp    closed http
113/tcp   open   auth
119/tcp   open   nntp
125/tcp   open   locus-map
143/tcp   open   imap
199/tcp   open   smux
256/tcp   open   fw1-secureremote
416/tcp   open   silverplatter
443/tcp   closed https
515/tcp   open   printer
554/tcp   open   rtsp
587/tcp   open   submission
992/tcp   open   telnets
993/tcp   open   imaps
995/tcp   open   pop3s
1009/tcp  open   unknown
1033/tcp  open   netinfo
1037/tcp  open   unknown
1067/tcp  open   instl_boots
1079/tcp  open   unknown
1112/tcp  open   msql
1147/tcp  open   unknown
1151/tcp  open   unknown
1322/tcp  open   unknown
1556/tcp  open   unknown
1720/tcp  open   H.323/Q.931
1935/tcp  open   rtmp
2005/tcp  open   deslogin
2179/tcp  open   unknown
2323/tcp  open   unknown
2638/tcp  open   sybase
2717/tcp  open   unknown
3001/tcp  open   nessus
3261/tcp  open   unknown
3306/tcp  open   mysql
3389/tcp  open   ms-term-serv
3880/tcp  open   unknown
5718/tcp  open   unknown
5811/tcp  open   unknown
5900/tcp  open   vnc
5902/tcp  open   vnc-2
6123/tcp  open   unknown
6881/tcp  open   bittorrent-tracker
7025/tcp  open   unknown
8080/tcp  open   http-proxy
8087/tcp  open   unknown
8099/tcp  open   unknown
8291/tcp  open   unknown
8652/tcp  open   unknown
9011/tcp  open   unknown
9040/tcp  open   tor-trans
9101/tcp  open   jetdirect
10012/tcp open   unknown
10626/tcp open   unknown
13782/tcp open   netbackup
21571/tcp open   unknown
22939/tcp open   unknown
40193/tcp open   unknown
41511/tcp open   unknown
44443/tcp open   coldfusion-auth
45100/tcp open   unknown
50389/tcp open   unknown
52848/tcp open   unknown
54045/tcp open   unknown
61900/tcp open   unknown

Nmap scan report for 216.195.0.89
Host is up (0.24s latency).
Not shown: 958 closed ports
PORT      STATE    SERVICE
9/tcp     open     discard
33/tcp    open     dsp
84/tcp    open     ctf
109/tcp   open     pop2
119/tcp   open     nntp
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
445/tcp   filtered microsoft-ds
667/tcp   open     unknown
901/tcp   open     samba-swat
995/tcp   open     pop3s
1023/tcp  open     netvenuechat
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1037/tcp  open     unknown
1079/tcp  open     unknown
1102/tcp  open     unknown
1112/tcp  open     msql
1117/tcp  open     unknown
1141/tcp  open     unknown
1185/tcp  open     unknown
1556/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
1935/tcp  open     rtmp
2005/tcp  open     deslogin
2034/tcp  open     scoremgr
2103/tcp  open     zephyr-clt
2717/tcp  open     unknown
4002/tcp  open     mlchat-proxy
4444/tcp  filtered krb524
5679/tcp  open     activesync
5902/tcp  open     vnc-2
6005/tcp  open     X11:5
8192/tcp  open     sophos
9877/tcp  open     unknown
20828/tcp open     unknown
25734/tcp open     unknown
41511/tcp open     unknown
49400/tcp open     compaqdiag
52848/tcp open     unknown
58080/tcp open     unknown

Nmap scan report for 216.195.0.90
Host is up (0.080s latency).
Not shown: 954 closed ports
PORT      STATE    SERVICE
22/tcp    open     ssh
111/tcp   open     rpcbind
119/tcp   open     nntp
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
443/tcp   open     https
445/tcp   filtered microsoft-ds
587/tcp   open     submission
995/tcp   open     pop3s
999/tcp   open     garcon
1023/tcp  open     netvenuechat
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1037/tcp  open     unknown
1079/tcp  open     unknown
1112/tcp  open     msql
1117/tcp  open     unknown
1259/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
1723/tcp  open     pptp
1935/tcp  open     rtmp
2005/tcp  open     deslogin
2007/tcp  open     dectalk
3283/tcp  open     netassistant
3580/tcp  open     unknown
3905/tcp  open     mupdate
4003/tcp  open     unknown
4444/tcp  filtered krb524
5003/tcp  open     filemaker
5902/tcp  open     vnc-2
7402/tcp  open     unknown
8080/tcp  open     http-proxy
8084/tcp  open     unknown
8180/tcp  open     unknown
8500/tcp  open     unknown
8654/tcp  open     unknown
9101/tcp  open     jetdirect
13783/tcp open     netbackup
14442/tcp open     unknown
18040/tcp open     unknown
32781/tcp open     unknown
41511/tcp open     unknown
50389/tcp open     unknown
52848/tcp open     unknown
54045/tcp open     unknown

Nmap scan report for 216.195.0.91
Host is up (0.027s latency).
Not shown: 961 closed ports
PORT      STATE    SERVICE
119/tcp   open     nntp
125/tcp   open     locus-map
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
445/tcp   filtered microsoft-ds
1009/tcp  open     unknown
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1037/tcp  open     unknown
1067/tcp  open     instl_boots
1079/tcp  open     unknown
1112/tcp  open     msql
1147/tcp  open     unknown
1217/tcp  open     unknown
1556/tcp  open     unknown
1719/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
1935/tcp  open     rtmp
2005/tcp  open     deslogin
3261/tcp  open     unknown
3869/tcp  open     unknown
3880/tcp  open     unknown
4444/tcp  filtered krb524
5902/tcp  open     vnc-2
6123/tcp  open     unknown
6788/tcp  open     unknown
6881/tcp  open     bittorrent-tracker
8087/tcp  open     unknown
8099/tcp  open     unknown
8652/tcp  open     unknown
9101/tcp  open     jetdirect
10626/tcp open     unknown
16992/tcp open     unknown
22939/tcp open     unknown
44443/tcp open     coldfusion-auth
52848/tcp open     unknown
54045/tcp open     unknown
61900/tcp open     unknown

Nmap scan report for 216.195.0.92
Host is up (0.15s latency).
Not shown: 953 closed ports
PORT      STATE    SERVICE
9/tcp     open     discard
33/tcp    open     dsp
84/tcp    open     ctf
109/tcp   open     pop2
111/tcp   open     rpcbind
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
445/tcp   filtered microsoft-ds
515/tcp   open     printer
667/tcp   open     unknown
901/tcp   open     samba-swat
995/tcp   open     pop3s
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1037/tcp  open     unknown
1079/tcp  open     unknown
1102/tcp  open     unknown
1112/tcp  open     msql
1141/tcp  open     unknown
1185/tcp  open     unknown
1309/tcp  open     unknown
1556/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
1723/tcp  open     pptp
2005/tcp  open     deslogin
2103/tcp  open     zephyr-clt
2179/tcp  open     unknown
2522/tcp  open     unknown
2717/tcp  open     unknown
3001/tcp  open     nessus
3017/tcp  open     unknown
3324/tcp  open     unknown
4444/tcp  filtered krb524
5679/tcp  open     activesync
5718/tcp  open     unknown
5811/tcp  open     unknown
5902/tcp  open     vnc-2
8291/tcp  open     unknown
9011/tcp  open     unknown
13782/tcp open     netbackup
25734/tcp open     unknown
41511/tcp open     unknown
45100/tcp open     unknown
50003/tcp open     unknown
50389/tcp open     unknown
58080/tcp open     unknown

Nmap scan report for 216.195.0.93
Host is up (0.13s latency).
Not shown: 961 closed ports
PORT      STATE    SERVICE
22/tcp    open     ssh
110/tcp   open     pop3
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
416/tcp   open     silverplatter
443/tcp   open     https
445/tcp   filtered microsoft-ds
992/tcp   open     telnets
999/tcp   open     garcon
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1033/tcp  open     netinfo
1082/tcp  open     unknown
1300/tcp  open     unknown
1322/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
2007/tcp  open     dectalk
2179/tcp  open     unknown
2323/tcp  open     unknown
2638/tcp  open     sybase
3905/tcp  open     mupdate
3998/tcp  open     unknown
4444/tcp  filtered krb524
5718/tcp  open     unknown
6156/tcp  open     unknown
7025/tcp  open     unknown
7402/tcp  open     unknown
8084/tcp  open     unknown
8180/tcp  open     unknown
8654/tcp  open     unknown
9011/tcp  open     unknown
9040/tcp  open     tor-trans
10012/tcp open     unknown
13783/tcp open     netbackup
18040/tcp open     unknown
21571/tcp open     unknown
32781/tcp open     unknown
45100/tcp open     unknown

Nmap scan report for 216.195.0.94
Host is up (0.14s latency).
Not shown: 955 closed ports
PORT      STATE    SERVICE
22/tcp    open     ssh
119/tcp   open     nntp
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
416/tcp   open     silverplatter
443/tcp   open     https
445/tcp   filtered microsoft-ds
901/tcp   open     samba-swat
992/tcp   open     telnets
999/tcp   open     garcon
1023/tcp  open     netvenuechat
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1033/tcp  open     netinfo
1067/tcp  open     instl_boots
1082/tcp  open     unknown
1112/tcp  open     msql
1117/tcp  open     unknown
1217/tcp  open     unknown
1718/tcp  open     unknown
1719/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
1935/tcp  open     rtmp
2042/tcp  open     isis
2601/tcp  open     zebra
2607/tcp  open     unknown
3998/tcp  open     unknown
4002/tcp  open     mlchat-proxy
4444/tcp  filtered krb524
4662/tcp  open     edonkey
5001/tcp  open     commplex-link
7007/tcp  open     afs3-bos
8084/tcp  open     unknown
8087/tcp  open     unknown
8180/tcp  open     unknown
8443/tcp  open     https-alt
8654/tcp  open     unknown
10012/tcp open     unknown
13783/tcp open     netbackup
16992/tcp open     unknown
21571/tcp open     unknown
50389/tcp open     unknown
52848/tcp open     unknown
61900/tcp open     unknown

Nmap scan report for 216.195.0.95
Host is up (0.23s latency).
Not shown: 954 closed ports
PORT      STATE    SERVICE
9/tcp     open     discard
84/tcp    open     ctf
109/tcp   open     pop2
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
445/tcp   filtered microsoft-ds
667/tcp   open     unknown
901/tcp   open     samba-swat
1023/tcp  open     netvenuechat
1025/tcp  filtered NFS-or-IIS
1026/tcp  filtered LSA-or-nterm
1027/tcp  filtered IIS
1067/tcp  open     instl_boots
1102/tcp  open     unknown
1117/tcp  open     unknown
1147/tcp  open     unknown
1185/tcp  open     unknown
1217/tcp  open     unknown
1309/tcp  open     unknown
1556/tcp  open     unknown
1719/tcp  open     unknown
1720/tcp  filtered H.323/Q.931
2005/tcp  open     deslogin
2103/tcp  open     zephyr-clt
2607/tcp  open     unknown
2717/tcp  open     unknown
3017/tcp  open     unknown
3869/tcp  open     unknown
3945/tcp  open     unknown
4002/tcp  open     mlchat-proxy
4444/tcp  filtered krb524
5679/tcp  open     activesync
5811/tcp  open     unknown
6005/tcp  open     X11:5
6123/tcp  open     unknown
6788/tcp  open     unknown
7007/tcp  open     afs3-bos
8087/tcp  open     unknown
8291/tcp  open     unknown
8652/tcp  open     unknown
9877/tcp  open     unknown
10626/tcp open     unknown
14442/tcp open     unknown
16992/tcp open     unknown
20828/tcp open     unknown
25734/tcp open     unknown

Nmap scan report for rtr01-f1-1.townisp.com (216.195.0.129)
Host is up (0.21s latency).
Not shown: 998 closed ports
PORT     STATE    SERVICE
1720/tcp filtered H.323/Q.931
5904/tcp filtered unknown

Nmap scan report for helpdesk.townisp.com (216.195.0.130)
Host is up (0.26s latency).
Not shown: 991 closed ports
PORT      STATE    SERVICE
22/tcp    open     ssh
37/tcp    open     time
53/tcp    open     domain
80/tcp    open     http
111/tcp   open     rpcbind
1720/tcp  filtered H.323/Q.931
4045/tcp  open     lockd
5432/tcp  open     postgresql
32771/tcp open     sometimes-rpc5

Nmap scan report for slb.townisp.com (216.195.0.131)
Host is up (0.20s latency).
Not shown: 990 filtered ports
PORT    STATE SERVICE
25/tcp  open  smtp
53/tcp  open  domain
80/tcp  open  http
110/tcp open  pop3
143/tcp open  imap
443/tcp open  https
465/tcp open  smtps
587/tcp open  submission
993/tcp open  imaps
995/tcp open  pop3s

Nmap scan report for ns1a.townisp.com (216.195.0.132)
Host is up (0.21s latency).
Not shown: 980 closed ports
PORT      STATE    SERVICE
21/tcp    open     ftp
22/tcp    open     ssh
25/tcp    open     smtp
37/tcp    open     time
53/tcp    open     domain
80/tcp    open     http
110/tcp   open     pop3
111/tcp   open     rpcbind
143/tcp   open     imap
443/tcp   open     https
465/tcp   open     smtps
587/tcp   open     submission
993/tcp   open     imaps
995/tcp   open     pop3s
1720/tcp  filtered H.323/Q.931
2049/tcp  open     nfs
3306/tcp  open     mysql
4045/tcp  open     lockd
8001/tcp  open     unknown
32771/tcp open     sometimes-rpc5

Nmap scan report for ns1b.townisp.com (216.195.0.133)
Host is up (0.21s latency).
Not shown: 980 closed ports
PORT      STATE    SERVICE
21/tcp    open     ftp
22/tcp    open     ssh
25/tcp    open     smtp
37/tcp    open     time
53/tcp    open     domain
80/tcp    open     http
110/tcp   open     pop3
111/tcp   open     rpcbind
143/tcp   open     imap
443/tcp   open     https
465/tcp   open     smtps
587/tcp   open     submission
993/tcp   open     imaps
995/tcp   open     pop3s
1720/tcp  filtered H.323/Q.931
2049/tcp  open     nfs
3306/tcp  open     mysql
4045/tcp  open     lockd
8001/tcp  open     unknown
32771/tcp open     sometimes-rpc5

Nmap scan report for ns2a.townisp.com (216.195.0.134)
Host is up (0.027s latency).
Not shown: 983 closed ports
PORT      STATE    SERVICE
21/tcp    open     ftp
22/tcp    open     ssh
25/tcp    open     smtp
37/tcp    open     time
53/tcp    open     domain
80/tcp    open     http
110/tcp   open     pop3
111/tcp   open     rpcbind
143/tcp   open     imap
443/tcp   open     https
465/tcp   open     smtps
587/tcp   open     submission
993/tcp   open     imaps
995/tcp   open     pop3s
1720/tcp  filtered H.323/Q.931
4045/tcp  open     lockd
32771/tcp open     sometimes-rpc5

Nmap scan report for ns2b.townisp.com (216.195.0.135)
Host is up (0.22s latency).
Not shown: 983 closed ports
PORT      STATE    SERVICE
21/tcp    open     ftp
22/tcp    open     ssh
25/tcp    open     smtp
37/tcp    open     time
53/tcp    open     domain
80/tcp    open     http
110/tcp   open     pop3
111/tcp   open     rpcbind
143/tcp   open     imap
443/tcp   open     https
465/tcp   open     smtps
587/tcp   open     submission
993/tcp   open     imaps
995/tcp   open     pop3s
1720/tcp  filtered H.323/Q.931
4045/tcp  open     lockd
32771/tcp open     sometimes-rpc5

Nmap scan report for ns3a.townisp.com (216.195.0.136)
Host is up (0.22s latency).
Not shown: 982 closed ports
PORT      STATE    SERVICE
21/tcp    open     ftp
22/tcp    open     ssh
25/tcp    open     smtp
37/tcp    open     time
53/tcp    open     domain
80/tcp    open     http
110/tcp   open     pop3
111/tcp   open     rpcbind
143/tcp   open     imap
443/tcp   open     https
465/tcp   open     smtps
587/tcp   open     submission
993/tcp   open     imaps
995/tcp   open     pop3s
1720/tcp  filtered H.323/Q.931
4045/tcp  open     lockd
32771/tcp open     sometimes-rpc5
32772/tcp open     sometimes-rpc7

Nmap scan report for ns3b.townisp.com (216.195.0.137)
Host is up (0.055s latency).
Not shown: 982 closed ports
PORT      STATE    SERVICE
21/tcp    open     ftp
22/tcp    open     ssh
25/tcp    open     smtp
37/tcp    open     time
53/tcp    open     domain
80/tcp    open     http
110/tcp   open     pop3
111/tcp   open     rpcbind
143/tcp   open     imap
443/tcp   open     https
465/tcp   open     smtps
587/tcp   open     submission
993/tcp   open     imaps
995/tcp   open     pop3s
1720/tcp  filtered H.323/Q.931
4045/tcp  open     lockd
32771/tcp open     sometimes-rpc5
32772/tcp open     sometimes-rpc7

Nmap scan report for ns4a.townisp.com (216.195.0.138)
Host is up (0.13s latency).
Not shown: 979 closed ports
PORT      STATE    SERVICE
21/tcp    open     ftp
22/tcp    open     ssh
25/tcp    open     smtp
37/tcp    open     time
53/tcp    open     domain
80/tcp    open     http
110/tcp   open     pop3
111/tcp   open     rpcbind
143/tcp   open     imap
443/tcp   open     https
465/tcp   open     smtps
587/tcp   open     submission
993/tcp   open     imaps
995/tcp   open     pop3s
1720/tcp  filtered H.323/Q.931
2049/tcp  open     nfs
3306/tcp  open     mysql
4045/tcp  open     lockd
8001/tcp  open     unknown
9001/tcp  open     tor-orport
32771/tcp open     sometimes-rpc5

Nmap scan report for ns4b.townisp.com (216.195.0.139)
Host is up (0.22s latency).
Not shown: 979 closed ports
PORT      STATE    SERVICE
21/tcp    open     ftp
22/tcp    open     ssh
25/tcp    open     smtp
37/tcp    open     time
53/tcp    open     domain
80/tcp    open     http
110/tcp   open     pop3
111/tcp   open     rpcbind
143/tcp   open     imap
443/tcp   open     https
465/tcp   open     smtps
587/tcp   open     submission
993/tcp   open     imaps
995/tcp   open     pop3s
1720/tcp  filtered H.323/Q.931
2049/tcp  open     nfs
3306/tcp  open     mysql
4045/tcp  open     lockd
8001/tcp  open     unknown
9001/tcp  open     tor-orport
32771/tcp open     sometimes-rpc5

Nmap scan report for ns5a.townisp.com (216.195.0.140)
Host is up (0.058s latency).
Not shown: 979 closed ports
PORT      STATE    SERVICE
21/tcp    open     ftp
22/tcp    open     ssh
25/tcp    open     smtp
37/tcp    open     time
53/tcp    open     domain
80/tcp    open     http
110/tcp   open     pop3
111/tcp   open     rpcbind
143/tcp   open     imap
443/tcp   open     https
465/tcp   open     smtps
587/tcp   open     submission
993/tcp   open     imaps
995/tcp   open     pop3s
1720/tcp  filtered H.323/Q.931
2049/tcp  open     nfs
3306/tcp  open     mysql
4045/tcp  open     lockd
8001/tcp  open     unknown
9001/tcp  open     tor-orport
32771/tcp open     sometimes-rpc5

Nmap scan report for ns5b.townisp.com (216.195.0.141)
Host is up (0.22s latency).
Not shown: 979 closed ports
PORT      STATE    SERVICE
21/tcp    open     ftp
22/tcp    open     ssh
25/tcp    open     smtp
37/tcp    open     time
53/tcp    open     domain
80/tcp    open     http
110/tcp   open     pop3
111/tcp   open     rpcbind
143/tcp   open     imap
443/tcp   open     https
465/tcp   open     smtps
587/tcp   open     submission
993/tcp   open     imaps
995/tcp   open     pop3s
1720/tcp  filtered H.323/Q.931
2049/tcp  open     nfs
3306/tcp  open     mysql
4045/tcp  open     lockd
8001/tcp  open     unknown
9001/tcp  open     tor-orport
32771/tcp open     sometimes-rpc5

Nmap scan report for t2001a.townisp.com (216.195.0.142)
Host is up (0.15s latency).
Not shown: 988 closed ports
PORT      STATE    SERVICE
22/tcp    open     ssh
25/tcp    open     smtp
53/tcp    open     domain
79/tcp    open     finger
111/tcp   open     rpcbind
514/tcp   open     shell
1720/tcp  filtered H.323/Q.931
2049/tcp  open     nfs
3306/tcp  open     mysql
4045/tcp  open     lockd
32772/tcp open     sometimes-rpc7
32776/tcp open     sometimes-rpc15

Nmap scan report for t2001b.townisp.com (216.195.0.143)
Host is up (0.035s latency).
Not shown: 988 closed ports
PORT      STATE    SERVICE
22/tcp    open     ssh
25/tcp    open     smtp
53/tcp    open     domain
79/tcp    open     finger
111/tcp   open     rpcbind
514/tcp   open     shell
1720/tcp  filtered H.323/Q.931
2049/tcp  open     nfs
3306/tcp  open     mysql
4045/tcp  open     lockd
32772/tcp open     sometimes-rpc7
32776/tcp open     sometimes-rpc15

Nmap scan report for t2002a.townisp.com (216.195.0.144)
Host is up (0.13s latency).
Not shown: 987 closed ports
PORT      STATE    SERVICE
22/tcp    open     ssh
25/tcp    open     smtp
53/tcp    open     domain
79/tcp    open     finger
111/tcp   open     rpcbind
513/tcp   open     login
514/tcp   open     shell
1720/tcp  filtered H.323/Q.931
3306/tcp  open     mysql
4045/tcp  open     lockd
32771/tcp open     sometimes-rpc5
32772/tcp open     sometimes-rpc7
32773/tcp open     sometimes-rpc9

Nmap scan report for t2002b.townisp.com (216.195.0.145)
Host is up (0.11s latency).
Not shown: 987 closed ports
PORT      STATE    SERVICE
22/tcp    open     ssh
25/tcp    open     smtp
53/tcp    open     domain
79/tcp    open     finger
111/tcp   open     rpcbind
513/tcp   open     login
514/tcp   open     shell
1720/tcp  filtered H.323/Q.931
3306/tcp  open     mysql
4045/tcp  open     lockd
32771/tcp open     sometimes-rpc5
32772/tcp open     sometimes-rpc7
32773/tcp open     sometimes-rpc9

Nmap scan report for prefix2.townisp.com (216.195.0.146)
Host is up (0.074s latency).
Not shown: 997 closed ports
PORT     STATE    SERVICE
22/tcp   open     ssh
25/tcp   open     smtp
1720/tcp filtered H.323/Q.931

Nmap scan report for prefix1.townisp.com (216.195.0.148)
Host is up (0.083s latency).
Not shown: 996 closed ports
PORT     STATE    SERVICE
22/tcp   open     ssh
25/tcp   open     smtp
873/tcp  open     rsync
1720/tcp filtered H.323/Q.931

Nmap scan report for monitor.townisp.com (216.195.0.150)
Host is up (0.079s latency).
Not shown: 996 closed ports
PORT     STATE    SERVICE
22/tcp   open     ssh
80/tcp   open     http
514/tcp  open     shell
1720/tcp filtered H.323/Q.931

Nmap scan report for voipns1.townisp.com (216.195.0.151)
Host is up (0.070s latency).
Not shown: 988 closed ports
PORT      STATE    SERVICE
22/tcp    open     ssh
25/tcp    open     smtp
37/tcp    open     time
53/tcp    open     domain
111/tcp   open     rpcbind
465/tcp   open     smtps
587/tcp   open     submission
1720/tcp  filtered H.323/Q.931
2049/tcp  open     nfs
4045/tcp  open     lockd
32771/tcp open     sometimes-rpc5
32774/tcp open     sometimes-rpc11

Nmap scan report for voipns2.townisp.com (216.195.0.152)
Host is up (0.082s latency).
Not shown: 987 closed ports
PORT      STATE    SERVICE
22/tcp    open     ssh
25/tcp    open     smtp
37/tcp    open     time
53/tcp    open     domain
111/tcp   open     rpcbind
465/tcp   open     smtps
587/tcp   open     submission
1720/tcp  filtered H.323/Q.931
2049/tcp  open     nfs
4045/tcp  open     lockd
9001/tcp  open     tor-orport
32771/tcp open     sometimes-rpc5
32775/tcp open     sometimes-rpc13

Nmap scan report for 216.195.0.154
Host is up (0.097s latency).
Not shown: 998 filtered ports
PORT    STATE SERVICE
443/tcp open  https
444/tcp open  snpp

Nmap scan report for webmail1.townisp.com (216.195.0.156)
Host is up (0.080s latency).
Not shown: 995 closed ports
PORT     STATE    SERVICE
22/tcp   open     ssh
80/tcp   open     http
111/tcp  open     rpcbind
443/tcp  open     https
1720/tcp filtered H.323/Q.931

Nmap scan report for webmail2.townisp.com (216.195.0.157)
Host is up (0.070s latency).
Not shown: 995 closed ports
PORT     STATE    SERVICE
22/tcp   open     ssh
80/tcp   open     http
111/tcp  open     rpcbind
443/tcp  open     https
1720/tcp filtered H.323/Q.931

Nmap scan report for webmail3.townisp.com (216.195.0.158)
Host is up (0.081s latency).
Not shown: 995 closed ports
PORT     STATE    SERVICE
22/tcp   open     ssh
80/tcp   open     http
111/tcp  open     rpcbind
443/tcp  open     https
1720/tcp filtered H.323/Q.931

Nmap scan report for ns6.townisp.com (216.195.0.161)
Host is up (0.11s latency).
Not shown: 980 closed ports
PORT      STATE    SERVICE
21/tcp    open     ftp
22/tcp    open     ssh
25/tcp    open     smtp
37/tcp    open     time
53/tcp    open     domain
80/tcp    open     http
110/tcp   open     pop3
111/tcp   open     rpcbind
143/tcp   open     imap
443/tcp   open     https
465/tcp   open     smtps
587/tcp   open     submission
993/tcp   open     imaps
995/tcp   open     pop3s
1720/tcp  filtered H.323/Q.931
2049/tcp  open     nfs
3306/tcp  open     mysql
4045/tcp  open     lockd
8001/tcp  open     unknown
32771/tcp open     sometimes-rpc5

Nmap scan report for ns6b.townisp.com (216.195.0.162)
Host is up (0.12s latency).
Not shown: 980 closed ports
PORT      STATE    SERVICE
21/tcp    open     ftp
22/tcp    open     ssh
25/tcp    open     smtp
37/tcp    open     time
53/tcp    open     domain
80/tcp    open     http
110/tcp   open     pop3
111/tcp   open     rpcbind
143/tcp   open     imap
443/tcp   open     https
465/tcp   open     smtps
587/tcp   open     submission
993/tcp   open     imaps
995/tcp   open     pop3s
1720/tcp  filtered H.323/Q.931
2049/tcp  open     nfs
3306/tcp  open     mysql
4045/tcp  open     lockd
8001/tcp  open     unknown
32771/tcp open     sometimes-rpc5

Nmap scan report for ns7.townisp.com (216.195.0.163)
Host is up (0.12s latency).
Not shown: 983 closed ports
PORT      STATE    SERVICE
21/tcp    open     ftp
22/tcp    open     ssh
25/tcp    open     smtp
37/tcp    open     time
53/tcp    open     domain
80/tcp    open     http
110/tcp   open     pop3
111/tcp   open     rpcbind
143/tcp   open     imap
443/tcp   open     https
465/tcp   open     smtps
587/tcp   open     submission
993/tcp   open     imaps
995/tcp   open     pop3s
1720/tcp  filtered H.323/Q.931
4045/tcp  open     lockd
32771/tcp open     sometimes-rpc5

Nmap scan report for ns7b.townisp.com (216.195.0.164)
Host is up (0.033s latency).
Not shown: 983 closed ports
PORT      STATE    SERVICE
21/tcp    open     ftp
22/tcp    open     ssh
25/tcp    open     smtp
37/tcp    open     time
53/tcp    open     domain
80/tcp    open     http
110/tcp   open     pop3
111/tcp   open     rpcbind
143/tcp   open     imap
443/tcp   open     https
465/tcp   open     smtps
587/tcp   open     submission
993/tcp   open     imaps
995/tcp   open     pop3s
1720/tcp  filtered H.323/Q.931
4045/tcp  open     lockd
32771/tcp open     sometimes-rpc5

Nmap scan report for ns8.townisp.com (216.195.0.165)
Host is up (0.092s latency).
Not shown: 982 closed ports
PORT      STATE    SERVICE
21/tcp    open     ftp
22/tcp    open     ssh
25/tcp    open     smtp
37/tcp    open     time
53/tcp    open     domain
80/tcp    open     http
110/tcp   open     pop3
111/tcp   open     rpcbind
143/tcp   open     imap
443/tcp   open     https
465/tcp   open     smtps
587/tcp   open     submission
993/tcp   open     imaps
995/tcp   open     pop3s
1720/tcp  filtered H.323/Q.931
4045/tcp  open     lockd
32771/tcp open     sometimes-rpc5
32772/tcp open     sometimes-rpc7

Nmap scan report for ns8b.townisp.com (216.195.0.166)
Host is up (0.068s latency).
Not shown: 982 closed ports
PORT      STATE    SERVICE
21/tcp    open     ftp
22/tcp    open     ssh
25/tcp    open     smtp
37/tcp    open     time
53/tcp    open     domain
80/tcp    open     http
110/tcp   open     pop3
111/tcp   open     rpcbind
143/tcp   open     imap
443/tcp   open     https
465/tcp   open     smtps
587/tcp   open     submission
993/tcp   open     imaps
995/tcp   open     pop3s
1720/tcp  filtered H.323/Q.931
4045/tcp  open     lockd
32771/tcp open     sometimes-rpc5
32772/tcp open     sometimes-rpc7

Nmap scan report for smtp1.shrewsbury-ma.gov (216.195.0.191)
Host is up (0.070s latency).
Not shown: 994 closed ports
PORT     STATE    SERVICE
22/tcp   open     ssh
25/tcp   open     smtp
465/tcp  open     smtps
587/tcp  open     submission
1720/tcp filtered H.323/Q.931
2048/tcp filtered dls-monitor

Nmap scan report for 216.195.0.205
Host is up (0.072s latency).
Not shown: 996 closed ports
PORT     STATE    SERVICE
135/tcp  open     msrpc
139/tcp  open     netbios-ssn
1720/tcp filtered H.323/Q.931
3389/tcp open     ms-term-serv

Nmap scan report for 216.195.0.254
Host is up (0.11s latency).
Not shown: 999 closed ports
PORT     STATE    SERVICE
1720/tcp filtered H.323/Q.931

Nmap done: 256 IP addresses (83 hosts up) scanned in 400.26 seconds
